CREATE TABLE IF NOT EXISTS 'SOURCE' (
    'URL' TEXT NOT NULL,
    'LAST_FETCH' TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS 'CHANNELS' (
    'CHANNEL_ID' TEXT NOT NULL UNIQUE,
    'XUI_ID' TEXT NOT NULL,
    'TVG_ID' TEXT NOT NULL,
    'TVG_NAME' TEXT NOT NULL,
    'TVG_LOGO' TEXT NOT NULL,
    'GROUP_TITLE' TEXT NOT NULL,
    'NAME' TEXT NOT NULL,
    'URL' TEXT NOT NULL,
    PRIMARY KEY('CHANNEL_ID')
);

CREATE TABLE IF NOT EXISTS 'MOVIES' (
    'MOVIE_ID' TEXT NOT NULL UNIQUE,
    'XUI_ID' TEXT NOT NULL,
    'TVG_ID' TEXT NOT NULL,
    'TVG_NAME' TEXT NOT NULL,
    'TVG_LOGO' TEXT NOT NULL,
    'GROUP_TITLE' TEXT NOT NULL,
    'NAME' TEXT NOT NULL,
    'URL' TEXT NOT NULL,
    PRIMARY KEY('MOVIE_ID')
);

CREATE TABLE IF NOT EXISTS 'SHOWS' (
    'SHOW_ID' TEXT NOT NULL UNIQUE,
    'XUI_ID' TEXT NOT NULL,
    'TVG_ID' TEXT NOT NULL,
    'TVG_NAME' TEXT NOT NULL,
    'TVG_LOGO' TEXT NOT NULL,
    'GROUP_TITLE' TEXT NOT NULL,
    'NAME' TEXT NOT NULL,
    'URL' TEXT NOT NULL,
    'SEASON' INTEGER NOT NULL,
    'EPISODE' INTEGER NOT NULL,
    PRIMARY KEY('SHOW_ID')
);

INSERT INTO 'SOURCE' VALUES ('https://example.com', 'N/A');