CREATE TABLE IF NOT EXISTS 'SETTINGS' (
    'URL' TEXT NOT NULL,
    'LAST_FETCH' TEXT NOT NULL,
    'CHANNELS_SAVE_PATH' TEXT NOT NULL,
    'MOVIES_SAVE_PATH' TEXT NOT NULL,
    'SERIES_SAVE_PATH' TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS 'CHANNELS' (
    'CHANNEL_ID' TEXT NOT NULL UNIQUE,
    'XUI_ID' TEXT NOT NULL,
    'TVG_ID' TEXT NOT NULL,
    'TVG_NAME' TEXT NOT NULL,
    'TVG_LOGO' TEXT NOT NULL,
    'GROUP_TITLE' TEXT NOT NULL,
    'NAME' TEXT NOT NULL,
    'URL' TEXT NOT NULL,
    PRIMARY KEY('CHANNEL_ID')
);

CREATE TABLE IF NOT EXISTS 'FILTERS' (
    'FILTER_ID' INTEGER NOT NULL UNIQUE,
    'FILTER_TEXT' TEXT NOT NULL,
    'FILTER_TYPE' TEXT NOT NULL,
    PRIMARY KEY('FILTER_ID' AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS 'MOVIES' (
    'MOVIE_ID' TEXT NOT NULL UNIQUE,
    'XUI_ID' TEXT NOT NULL,
    'TVG_ID' TEXT NOT NULL,
    'TVG_NAME' TEXT NOT NULL,
    'TVG_LOGO' TEXT NOT NULL,
    'GROUP_TITLE' TEXT NOT NULL,
    'NAME' TEXT NOT NULL,
    'URL' TEXT NOT NULL,
    'FETCHED' INTEGER NOT NULL,
    PRIMARY KEY('MOVIE_ID')
);

CREATE TABLE IF NOT EXISTS 'SERIES' (
    'SERIES_ID' TEXT NOT NULL UNIQUE,
    'XUI_ID' TEXT NOT NULL,
    'TVG_ID' TEXT NOT NULL,
    'TVG_NAME' TEXT NOT NULL,
    'TVG_LOGO' TEXT NOT NULL,
    'GROUP_TITLE' TEXT NOT NULL,
    'NAME' TEXT NOT NULL,
    'URL' TEXT NOT NULL,
    'SEASON' INTEGER NOT NULL,
    'EPISODE' INTEGER NOT NULL,
    'FETCHED' INTEGER NOT NULL,
    PRIMARY KEY('SERIES_ID')
);

INSERT INTO SETTINGS VALUES ('https://example.com', 'N/A', '/data/playlist.m3u', '/data/movies', '/data/tv');